### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sj26** [sj26/rack-s3#1]
Hi there!

I really love the idea of your gem, but it didn't work for me with modern aws s3 and rack clients. So I rebuilt it:
https://github.com/sj26/rack-s3

I was wondering if you would accept a pull request for a new version, or might consider handing over the gem name — it's a very good name!

Cheers,
Sam

**Comment by lmarburger** [comment]
That's great! I'll transfer it over but it looks like you'll need to rename/delete your fork first.
![image](https://user-images.githubusercontent.com/23582/92509921-03131180-f1d9-11ea-9caa-c13b967f3cee.png)

**Comment by sj26** [comment]
Amazing, thank you! I've just removed my fork.

This is me on rubygems, too:  
https://rubygems.org/profiles/sj26

**Comment by lmarburger** [comment]
Done! Added you as an owner to the rubygem. Feel free to remove me at your convenience.

![good luck](https://user-images.githubusercontent.com/23582/92527765-8fcbc880-f1f5-11ea-8ee5-cb9c717be944.gif)

**Comment by sj26** [comment]
Thanks @lmarburger! I'll take good care of it. :-)
